apiVersion : apps/v1
kind: Deployment
metadata:
 name: user-deployment
 labels:
  app: user
spec:
 replicas: 1
 selector:
  matchLabels: 
   service: user
 template:
  metadata:
   labels:
    service: user
  spec:
   containers:
   - name: user
     image: aquibchiniwala/userservicejaeger:v2
     ports:
     - containerPort: 80